services:
  web:
    build: ./
    command: ["./entrypoint.sh"]
    ports:
      - '8000:8000'
    env_file: .env
    depends_on:
      - db
  db:
    image: postgres
    ports:
      - '5432:5432'
    env_file: .env
    restart: always
    volumes:
      - ./db_django:/var/lib/postgres