version: '3'

services:
  web:
    build: ./
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - '8000:8000'
    depends_on:
      - db
  db:
    image: postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: "booklib_db"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "130283BVA"
    restart: always
    volumes:
      - ./db_django:/var/lib/postgres