# Generated by Django 5.1.2 on 2024-10-13 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_rename_name_author_title_rename_name_book_title_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='quantity',
            new_name='count',
        ),
    ]
