# Generated by Django 5.1.2 on 2024-10-15 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_rename_quantity_book_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='imageBooks/', verbose_name='Изображение'),
        ),
    ]
